apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "256Mi"  # Memory should be specified with units (Mi, Gi)
    limits.cpu: "2"
    limits.memory: "512Mi"