# Deployment for python-api
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
spec:
  replicas: 3  # Initial number of replicas
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      automountServiceAccountToken: false
      containers:
        - name: python-api
          image: tiangolo/uvicorn-gunicorn-fastapi:python3.11
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: TZ
              value: "Europe/Paris"
            - name: MONGO_URL
              value: mongodb://mongodb:27017
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
---
# Service for python-api
apiVersion: v1
kind: Service
metadata:
  name: python-api
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: python-api