apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: development  # Specify the namespace
  name: read-only-role    # Name of the role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]  # Read-only access to pods