# Horizontal Pod Autoscaler for python-api
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: python-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-api   # Targeting the python-api Deployment
  minReplicas: 1        # Minimum number of replicas
  maxReplicas: 5        # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu        # Scaling based on CPU utilization
        target:
          type: Utilization
          averageUtilization: 50  # Target 50% CPU utilization